---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "allure-ee.fullname" . }}
  labels:
    app: {{ template "allure-ee.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ .Values.username | b64enc | quote }}
{{- if .Values.password }}
  password: {{ .Values.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
{{- if .Values.jwtSecret }}
  jwtSecret: {{ .Values.jwtSecret | b64enc | quote }}
{{- else }}
  jwtSecret: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}
{{- range $name, $value := .Values.gateway.env.secret }}
{{- if not (empty $value) }}
  {{ printf "%s.%s" "gateway" $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- range $name, $value := .Values.uaa.env.secret }}
{{- if not (empty $value) }}
  {{ printf "%s.%s" "uaa" $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- range $name, $value := .Values.report.env.secret }}
{{- if not (empty $value) }}
  {{ printf "%s.%s" "report" $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
  rabbitUser: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  rabbitPass: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
{{- if .Values.postgresql.external }}
  uaaDbUser: {{ .Values.postgresql.external.uaaUsername | b64enc | quote }}
  uaaDbPass: {{ .Values.postgresql.external.uaaPassword | b64enc | quote }}
  reportDbUser: {{ .Values.postgresql.external.reportUsername | b64enc | quote }}
  reportDbPass: {{ .Values.postgresql.external.reportPassword | b64enc | quote }}
{{- else }}
  uaaDbUser: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  uaaDbPass: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  reportDbUser: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  reportDbPass: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
{{- if .Values.file_system.external }}
  s3AccessKey: {{ .Values.file_system.s3.accessKey | b64enc | quote }}
  s3SecretKey: {{ .Values.file_system.s3.secretKey | b64enc | quote }}
{{- else }}
  s3AccessKey: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  s3SecretKey:  {{ .Values.minio.auth.rootPassword | b64enc | quote }}
{{- end}}
