{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "allure-testops.name" . }}
  labels:
    app: {{ template "allure-testops.name" . }}
    chart: {{ template "allure-testops.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end -}}
