apiVersion: v2
name: allure-testops
version: 3.190.0
appVersion: 3.190.0

description: Allure TestOps

kubeVersion: '>= 1.14.0-0'

home: https://qameta.io
sources:
  - https://hub.docker.com/r/allure/allure-ui
  - https://hub.docker.com/r/allure/allure-uaa
  - https://hub.docker.com/r/allure/allure-report

maintainers:
  - name: eroshenkoam
    email: eroshenkoam@qameta.io
  - name: Andrey Ryoo
    email: andrey.ryoo@qameta.io

dependencies:
  - name: rabbitmq
    version: ~8.26.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: postgresql
    version: ~10.3.18
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~10.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: 10.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
