apiVersion: v2
name: allure-testops
version: 1.2.3
appVersion: 3.192.2

description: Allure TestOps

kubeVersion: '>= 1.14.0-0'

home: https://qameta.io
sources:
  - https://hub.docker.com/r/allure/allure-ui
  - https://hub.docker.com/r/allure/allure-uaa
  - https://hub.docker.com/r/allure/allure-report

maintainers:
  - name: eroshenkoam
    email: eroshenkoam@qameta.io
  - name: Andrey Ryoo
    email: andrey.ryoo@qameta.io

dependencies:
  - name: rabbitmq
    version: 8.27.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: postgresql
    version: 10.16.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: 10.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
