name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: "Helm publish"
          uses: mbovo/action-helm-tools@v1.0.0
          with:
            action: "push"
          env:
            CHART_DIR: charts/allure-testops
            ARTIFACTORY_URL: https://dl.qameta.io:443/artifactory/helm/
            ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
            ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASS }}
