name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      - name: Add Qameta Repo
        run: |
          helm repo add --username ${{ secrets.SA_NAME }} --password ${{ secrets.SA_PASS }}  qameta-artifactory https://dl.qameta.io/artifactory/helm

      - name: Install Publish Plugin
        run: |
          helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v1.0.2
          
      - name: Publish Chart
        run: |
          helm push-artifactory charts/allure-testops qameta-artifactory --access-token ${{ secrets.SA_ACCESS_TOKEN }} --skip-reindex
